name: Deploy Content to sentinellab2026 [62931b70-8073-47c0-b1bb-1fd4c064975d]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-62931b70-8073-47c0-b1bb-1fd4c064975d.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-62931b70-8073-47c0-b1bb-1fd4c064975d.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'seclabenv'
      workspaceName: 'sentinellab2026'
      workspaceId: '9d1afc3c-2e0e-4f87-9740-40b46c879117'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,Workbook,CustomDetection,Watchlist,Playbook,Parser,HuntingQuery,AutomationRule'
      branch: 'main'
      sourceControlId: '62931b70-8073-47c0-b1bb-1fd4c064975d'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_62931b70807347c0b1bb1fd4c064975d }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_62931b70807347c0b1bb1fd4c064975d }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_62931b70807347c0b1bb1fd4c064975d }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_62931b70807347c0b1bb1fd4c064975d }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_62931b70807347c0b1bb1fd4c064975d }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_62931b70807347c0b1bb1fd4c064975d }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_62931b70807347c0b1bb1fd4c064975d }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_62931b70807347c0b1bb1fd4c064975d }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_62931b70807347c0b1bb1fd4c064975d }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-62931b70-8073-47c0-b1bb-1fd4c064975d.ps1